[package]
name = "pantomath"
version = "0.1.0"
authors = ["post-rex <post-rex@pm.me>"]
edition = "2018"

[dependencies]
sodiumoxide = "^0.2.6"
snow = { version = "^0.8.0", features = ["libsodium-accelerated"] }
mimalloc = { version = "0.1.25", default-features = false }
tracing = "^0.1.26"
tracing-subscriber = "^0.2.18"
tracing-futures = "^0.2.5"

[dependencies.tokio]
version = "^1.6.2"
features = ["rt", "rt-multi-thread", "net", "macros"]

[profile.release]
lto = "fat"
codegen-units = 1
